api_server/lib/util/restful/model_creator.js, api_server/modules/posts/post_creator.js, api_server/modules/posts/test/post_post/codemarks/new_users_on_the_fly_test.js, api_server/modules/posts/test/post_post/reviews/new_users_on_the_fly_for_review_test.js, api_server/modules/users/test/post_user/post_user_test.js, api_server/modules/users/test/post_user/unregistered_invite_test.js, api_server/modules/users/user_attributes.js, api_server/modules/users/user_creator.js
[Changes reviewed on CodeStream](https://api.codestream.com/r/W75JY6zGmBhgt48D/OMXc2TfQQ-Oi4dqOs0xqQQ?src=GitHub) by brian on Jun 26, 2020
=> track lastInviteType and inviteTrigger for users

shared/codestream_configs/bin/mongo-config-loader.js, shared/codestream_configs/lib/structured_config_base.js, shared/codestream_configs/lib/structured_config_file.js, shared/codestream_configs/lib/structured_config_mongo.js
**This PR Addresses:**  
[StructuredMongoConfig to support notion of activation of a particular config](https://trello.com/c/J3mfAbi9/4734-structuredmongoconfig-to-support-notion-of-activation-of-a-particular-config)
=> Enhancements to support onprem-admin UI

api_server/modules/web/link_codemark_request.js, api_server/modules/web/link_review_request.js, api_server/modules/web/templates/login.hbs, api_server/modules/web/web_login_request.js, api_server/modules/web/web_provider_auth_request.js, api_server/modules/web/web_signin_request.js
this is for https://trello.com/c/8NSp8JHp/5451-add-new-webauth-displayed-segment-event
=> Add new "WebAuth Displayed" segment event

api_server/modules/web/templates/login.hbs
=> CDSTRM-1321: Make minor copy changes to login page

api_server/modules/web/styles/web.css, api_server/modules/web/templates/partial_launcher_detailed.hbs
redesign open-in-ide page with gif instead of video
=> feature/CDSTRM_1442 

api_server/modules/web/web_confirm_code_request.js
=> CDSTRM-1427: Load specified URL after code signin

outbound_email/src/codeErrorRenderer.js, outbound_email/src/codemarkRenderer.js, outbound_email/src/rendererBase.js, outbound_email/src/reviewRenderer.js
[Changes reviewed on CodeStream](https://staging-api.codestream.us/r/Ya5We-trHA5di0uy/5cDK_-7HQJiLQ0A1SNRCYQ?src=GitHub) by cstryker on Mar 16, 2022
=> CDSTRM-1562: Fix date for parent objects in emails

api_server/modules/web/templates/login.hbs
[Changes reviewed on CodeStream](https://staging-api.codestream.us/r/Ya5We-trHA5di0uy/FBdkOKM8ShCZbAJbxKKjxA?src=GitHub) by cstryker on Mar 17, 2022
=> CDSTRM-1647: Keep params when switching login mode

api_server/modules/cors/cors.js, api_server/modules/providers/msteams_conversation_bot.js
Also modifies CORS domains for azure.
=> NR-47935 -- Add external icon to links throughout bot

api_server/bin/cs_api-populate_nr_org_ids.js, api_server/modules/companies/add_nr_info_request.js, api_server/modules/companies/test/add_nr_info/add_nr_info_test.js, api_server/modules/companies/test/add_nr_info/add_to_existing_test.js, api_server/modules/companies/test/add_nr_info/common_init.js, api_server/modules/companies/test/add_nr_info/only_account_ids_test.js, api_server/modules/companies/test/add_nr_info/only_org_ids_test.js
=> Change NR org id handling

api_server/lib/oauth/oauth_module.js, api_server/modules/circleci_auth/circleci_auth.js, api_server/modules/circleci_auth/module.js, shared/server_utils/custom_config.js
=> Add CircleCI provider

api_server/modules/providers/provider_refresh_request.js
- Use the stored refresh token, not the refresh token sent by client.
**This PR Addresses:**  
[NEWRELIC-5914 User getting disconnected from Jira cloud](https://issues.newrelic.com/browse/NEWRELIC-5914)  
<sup> Created from JetBrains using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)</sup>
=> NEWRELIC-5914 User getting disconnected from Jira cloud

api_server/lib/api_server/api_request.js, api_server/lib/api_server/api_server.js, api_server/package-lock.json, api_server/package.json, outbound_email/package-lock.json, outbound_email/package.json
**This PR Addresses:**  
[NR-83870 Upgrade Server NewRelic agent to 9.8.1](https://issues.newrelic.com/browse/NR-83870)  
<sup> Created from JetBrains using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)</sup>
=> NR-83870 Upgrade Server NewRelic agent to 9.8.1

api_server/modules/jenkins_auth/jenkins_auth.js, api_server/modules/jenkins_auth/module.js, api_server/modules/providers/provider_test_constants.js, shared/server_utils/custom_config.js
The corresponding provider code in the extensions has not been merged, so theoretically, this won't impact any current clients.
=> Adding Jenkins as a provider

api_server/etc/msteamsbot/template/manifest.json, api_server/modules/providers/msteams_conversation_bot.js
Added NR.com to validDomains
Removed extraneous messages from bot
Incremement version for testing
=> MSTeams Bot Updates

api_server/etc/capabilities.js
**This PR Addresses:**  
[NR-104616 Add CS team-level feature flag](https://issues.newrelic.com/browse/NR-104616)  
<sup> Created from JetBrains using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)</sup>
=> NR-104616 Add CS team-level feature flag

api_server/lib/grok/errors.js, api_server/lib/grok/grok_client.js, api_server/modules/posts/test/post_post/code_errors/grok_prompted_analysis_reply_test.js
- Send every possible exception case back to client through pubnub
- Segment tracking updates
- Log errors/exceptions with NR backend
=> Updates for Grok

api_server/etc/capabilities.js
PR for NR-120267, to add feature flag for code analyzers
=> Add showCodeAnalyzers feature flag

api_server/etc/version_matrix.json
=> 14.20 Backend Release

api_server/modules/repos/repo.js, api_server/modules/repos/repo_creator.js
Wanted to centralize this into the actual NormalizeUrl method, but can't output an error there, which would have necessitated catching it in these places anyway.
=> Add some error handling in the codebase where we use NormalizeUrl.

api_server/etc/version_matrix.json
This reverts commit 88a5e4c0a522e4e595f8e67a5d582865900f31db.
=> Revert "minimum version to 15.0"

api_server/etc/version_matrix.json
This reverts commit e1e1ba9ced6d212412ceca7f86a02c0cd4b6a38b.
=> Revert "Revert "minimum version to 15.0""

api_server/package-lock.json, api_server/package.json, inbound_email/package-lock.json, inbound_email/package.json, outbound_email/package-lock.json, outbound_email/package.json
Add deps for node-vault and tiny-async-pool to all projects since they are req'd in shared startup code
=> inbound startup issue

shared/codestream_configs/parameters.json
=> NR-179717 Apply Fix / diff view

.vscode/launch.json, codestream-docker.json, enable-mailout.env.sh, shared/codestream_configs/parameters.json, start-api-server.sh
Add mechanism to setup local api sandbox so it will queue outbound email to sqs.
=> Support outbound email in dev sandbox

api_server/etc/capabilities.js
No longer needed; just using IDE as the gate from here on
=> Deprecating these flags

api_server/lib/grok/grok_client.js, api_server/modules/users/test/unsubscribe_notification/tracking_test.js, api_server/modules/users/test/unsubscribe_reminder/tracking_test.js, api_server/modules/users/test/unsubscribe_weekly/tracking_test.js, api_server/modules/users/unsubscribe_email_request.js, api_server/modules/web/templates/partial_launcher.hbs, api_server/modules/web/templates/partial_launcher_detailed.hbs
Updated server-side event names to comply with defined list of actions
=> Events 2.0 tweaks

api_server/lib/grok/grok_client.js, codestream-docker.json
=> NR-183484 Prevent suggestion of a code fix when the code is correct

api_server/modules/apiweb/newrelic_ide_redirect_request.js, api_server/modules/apiweb/templates/ide_redirect.hbs, api_server/modules/apiweb/templates/partial_launcher_detailed.hbs
https://new-relic.atlassian.net/browse/NR-262995
=> remove abtest, use tabs version only, log tab if pageType is logs, meta_data_5 removal

api_server/modules/posts/post_creator.js, api_server/modules/posts/post_post_request.js
- Mostly fix formatting to match existing formatting style
- Only real code change is `this.useId = existingPost.id;` in post_post_request.js
=> NR-270545 Not possible to make a post when 'ShowGrok' feature is off
